config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'reviews#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  def self.search_results(query)
    result = []
    Rails.logger.info 'input query - #{query}'
    if !query.empty?
  		review_hash = {}
  		query.each do |token|
  			reviews = Rails.cache.read(token)
  			if !reviews.nil?
  				reviews.each do |review|
            if review_hash.key?(review)
              review_hash[review] = review_hash[review][0] + 1
            else
              review_hash[review] = [1, review.score]
            end
  				end
  			end
  		end
      # sorting based o the calculated score , if its same then check document score
  		result = review_hash.sort_by{|k, v| [-v[0], -v[1]]}.first(20).map{ |review| review[0] }
    end
    result
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews =  Review.search_results(index_params)
    render 'index'
  end

  private

  def index_params
    params.permit(:query)
    params[:query].present? ? params[:query].split(',') : []
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/review_helper.rb
module ReviewHelper
  def self.trim_word(word)
		return word.gsub(",","").gsub(".","").gsub(";","").gsub("!","").gsub(/"/,"").gsub("(","").gsub(")","").gsub("<","").gsub(">","").gsub("/","").downcase
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_reviews.html.erb
<div style="margin-left:40px;margin-right:200px;font-size:15px;">

  <% @reviews.each do |review| %>
      <div class="header" style="color:#00B4CC;">
        <%= review.summary %>
      </div>
      <p><%= review.text%></p>
      <h5>Search score: <%= review.score %> | ProductId: <%= review.product_id %> | UserId: <%= review.user_id %> | Helpfulness: <%= review.helpfulness %> | Timestamp: <%= review.time %> </h5>
  <% end %>

</div>

app/views/reviews/index.html.erb
<p> input query format: query1, query2</p>
<div class="search">
  <%= form_tag(search_path, method: "get", id: "search-form") do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search", class: 'searchTerm' %>
    <p></p>
    <%= submit_tag "Search", :name => nil, :class => 'searchButton' %>
  <% end %>
</div>
    <p></p>
    <%= render 'reviews' %>